import {useEffect,useRef,useState,useCallback} from 'react';
import {TerminalSquare,Plus,PanelsTopLeft,X,ArrowRight,Check,Trash2,LogOut,Minus} from 'lucide-react';
import {api,Session,ApiError} from './api';
import {Login} from './Login';
import {KeyBar} from './KeyBar';
import {TerminalView,TerminalHandle,Connection} from './TerminalView';
type Sheet='new'|'sessions'|'settings'|'compose'|'copy'|null;
export default function App(){
 const [auth,setAuth]=useState<boolean|null>(null),[sessions,setSessions]=useState<Session[]>([]),[active,setActive]=useState(''),[status,setStatus]=useState<Connection>('connecting'),[sheet,setSheet]=useState<Sheet>(null),[name,setName]=useState(''),[draft,setDraft]=useState(''),[copyText,setCopyText]=useState(''),[font,setFont]=useState(()=>Number(localStorage.getItem('fontSize'))||13),[ctrl,setCtrl]=useState(false),[alt,setAlt]=useState(false),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[bootError,setBootError]=useState(false),[composing,setComposing]=useState(false),[confirmId,setConfirmId]=useState('');
 const term=useRef<TerminalHandle>(null),mod=useRef({ctrl,alt});mod.current={ctrl,alt};
 useEffect(()=>{const viewport=window.visualViewport;const update=()=>{document.documentElement.style.setProperty('--viewport-height',`${viewport?.height||window.innerHeight}px`);document.documentElement.style.setProperty('--viewport-top',`${viewport?.offsetTop||0}px`);};update();viewport?.addEventListener('resize',update);viewport?.addEventListener('scroll',update);window.addEventListener('resize',update);return()=>{viewport?.removeEventListener('resize',update);viewport?.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[]);
 const refresh=useCallback(async()=>{try{const {sessions:items}=await api<{sessions:Session[]}>('/sessions');setSessions(items);setActive(current=>items.some(s=>s.id===current)?current:items.find(s=>s.id===localStorage.getItem('sessionId'))?.id||items[0]?.id||'');}catch(e){if(e instanceof ApiError&&e.status===401)setAuth(false);else setToast('暂时无法连接 Mac，稍后可重试。');}},[]);
 const checkAuth=useCallback(()=>{setBootError(false);void api('/me').then(()=>setAuth(true)).catch(e=>{if(e instanceof ApiError&&e.status===401)setAuth(false);else setBootError(true);});},[]);useEffect(checkAuth,[checkAuth]);
 useEffect(()=>{if(auth)void refresh();},[auth,refresh]);
 useEffect(()=>{if(active)localStorage.setItem('sessionId',active);setCtrl(false);setAlt(false);},[active]);
 useEffect(()=>{localStorage.setItem('fontSize',String(font));},[font]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id);},[toast]);
 const transform=useCallback((data:string)=>{const {ctrl,alt}=mod.current;let value=data;if(ctrl&&value.length===1){const code=value.toUpperCase().charCodeAt(0);if(code>=64&&code<=95)value=String.fromCharCode(code-64);else if(value===' ')value='\0';}if(alt)value='\x1b'+value;mod.current={ctrl:false,alt:false};if(ctrl)setCtrl(false);if(alt)setAlt(false);return value;},[]);
 const open=(value:Sheet)=>{term.current?.blur();setConfirmId('');setSheet(value);};
 const create=async()=>{if(busy)return;setBusy(true);try{const {session}=await api<{session:Session}>('/sessions','POST',{name:name.trim()||`终端 ${sessions.length+1}`});await refresh();setActive(session.id);setSheet(null);setName('');}catch{setToast('无法创建会话，请确认 Mac 在线。');}finally{setBusy(false);}};
 const paste=async()=>{try{const value=await navigator.clipboard.readText();setDraft(value);open('compose');}catch{setDraft('');open('compose');setToast('请长按输入区，选择“粘贴”。');}};
 const copy=async()=>{setCopyText(term.current?.copy()||'');open('copy');if(active){try{const {text}=await api<{text:string}>(`/sessions/${active}/history`);setCopyText(text);}catch{setToast('无法读取完整历史，显示当前画面。');}}};
 const session=sessions.find(s=>s.id===active);
 const send=(value:string)=>{if(status!=='connected')return;term.current?.send(transform(value));};
 const sendDraft=(enter:boolean)=>{if(status!=='connected')return;if(new TextEncoder().encode(draft).length>30000){setToast('文本太长，请分段发送。');return;}const accepted=term.current?.paste(draft,enter);if(!accepted){setToast('连接已断开，输入已保留。');return;}setDraft('');setSheet(null);};
 if(auth===null)return <div className="boot"><TerminalSquare/><span>{bootError?'Mac 暂时离线':'正在连接…'}</span>{bootError&&<button onClick={checkAuth}>重新连接</button>}</div>;
 if(!auth)return <Login onLogin={()=>setAuth(true)}/>;
 return <main className="app"><header className="topbar"><TerminalSquare className="brand-icon" size={27}/><h1>MacBook Air</h1><span className={`status-dot ${active?status:'idle'}`} role="status" aria-label={!active?'未连接':status==='connected'?'已连接':status==='connecting'?'正在连接':'连接已断开'}/><div className="spacer"/><button aria-label="新建终端" onClick={()=>{setName('');open('new');}}><Plus/></button><button aria-label="管理会话" onClick={()=>{void refresh();open('sessions');}}><PanelsTopLeft size={22}/></button></header>
 <nav className="session-tabs" aria-label="终端会话">{sessions.map(s=><button key={s.id} aria-current={active===s.id?'page':undefined} className={active===s.id?'selected':''} onClick={()=>setActive(s.id)}>{s.name}</button>)}{!sessions.length&&<span>你的持久会话</span>}</nav>
 <section className="terminal-area">{active?<><TerminalView ref={term} sessionId={active} fontSize={font} onStatus={setStatus} onExpired={()=>setAuth(false)} onExit={()=>void refresh()} transform={transform}/>{status!=='connected'&&<div className="connection-banner" role="status">{status==='connecting'?'正在连接 Mac…':'连接中断，正在重连…'}<small>恢复后继续原会话</small></div>}</>:<div className="empty"><TerminalSquare size={38}/><h2>从一个终端开始</h2><p>运行 Claude Code、Codex 或日常命令。<br/>切到后台，再回来继续。</p><button className="primary" onClick={()=>{setName('主终端');open('new');}}><Plus size={19}/>新建终端</button></div>}</section>
 <KeyBar disabled={!active||status!=='connected'} ctrl={ctrl} alt={alt} toggleCtrl={()=>setCtrl(!ctrl)} toggleAlt={()=>setAlt(!alt)} send={send} compose={()=>open('compose')} paste={()=>void paste()} copy={()=>void copy()} settings={()=>open('settings')} focus={()=>term.current?.focus()}/>
 {toast&&<div className="toast" role="status">{toast}</div>}
 {sheet&&<div className="sheet-backdrop" onClick={e=>{if(e.target===e.currentTarget)setSheet(null);}}><section className="sheet" role="dialog" aria-modal="true" aria-label={{new:'新建终端',sessions:'管理会话',settings:'终端设置',compose:'输入',copy:'复制终端内容'}[sheet]}><header><h2>{{new:'新建终端',sessions:'会话',settings:'终端设置',compose:'输入',copy:'复制终端内容'}[sheet]}</h2><button aria-label="关闭" onClick={()=>setSheet(null)}><X size={22}/></button></header>
 {sheet==='new'&&<form onSubmit={e=>{e.preventDefault();void create();}}><label htmlFor="session-name">会话名称</label><input id="session-name" autoFocus value={name} maxLength={48} onChange={e=>setName(e.target.value)} placeholder="例如：Claude、开发、主终端"/><p className="hint">会话运行在你的 Mac 上。关闭网页不会结束会话。</p><button className="primary" disabled={busy}>{busy?'正在创建…':'创建会话'}<ArrowRight size={18}/></button></form>}
 {sheet==='compose'&&<><textarea autoFocus onCompositionStart={()=>setComposing(true)} onCompositionEnd={()=>setComposing(false)} aria-label="待发送文本" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="输入中文、长命令，或长按粘贴…" rows={5} autoCapitalize="none" autoCorrect="off" spellCheck={false}/><p className="hint">发送文本不带回车；“发送并回车”会提交当前输入。</p><div className="action-row"><button disabled={composing||!draft||status!=='connected'} onClick={()=>sendDraft(false)}>发送文本</button><button className="primary" disabled={composing||status!=='connected'} onClick={()=>sendDraft(true)}>发送并回车<ArrowRight size={18}/></button></div></>}
 {sheet==='copy'&&<><textarea aria-label="可复制的终端内容" readOnly value={copyText} rows={8} onFocus={e=>e.target.select()}/><p className="hint">显示此会话保留的终端历史，断线重连后仍可查看。</p><button className="primary" onClick={()=>void navigator.clipboard.writeText(copyText).then(()=>setToast('已复制')).catch(()=>setToast('请长按文本，使用系统复制。'))}>复制文本</button></>}
 {sheet==='sessions'&&<><div className="session-list">{sessions.map(s=><div className="session-row" key={s.id}><button className="session-select" onClick={()=>{setActive(s.id);setSheet(null);}}><TerminalSquare size={19}/><span>{s.name}</span>{active===s.id&&<Check size={17}/>}</button><button className="danger-icon" aria-label={`结束 ${s.name}`} onClick={()=>setConfirmId(s.id)}><Trash2 size={18}/></button>{confirmId===s.id&&<div className="confirm"><p>结束“{s.name}”及其中运行的程序？</p><button onClick={()=>setConfirmId('')}>取消</button><button className="danger" onClick={async()=>{try{await api(`/sessions/${s.id}`,'DELETE');setConfirmId('');await refresh();}catch{setToast('结束会话失败，请重试。');}}}>结束会话</button></div>}</div>)}</div><button className="wide" onClick={()=>{setName('');setSheet('new');}}><Plus size={18}/>新建会话</button></>}
 {sheet==='settings'&&<><div className="setting-row"><span>终端字号</span><button aria-label="减小字号" disabled={font<=10} onClick={()=>setFont(Math.max(10,font-1))}><Minus size={18}/></button><output>{font}</output><button aria-label="增大字号" disabled={font>=24} onClick={()=>setFont(Math.min(24,font+1))}><Plus size={18}/></button></div>{session&&<form onSubmit={async e=>{e.preventDefault();const target=e.currentTarget.elements.namedItem('rename') as HTMLInputElement;try{await api(`/sessions/${session.id}`,'PATCH',{name:target.value.trim()});await refresh();setToast('会话名称已更新');}catch{setToast('重命名失败');}}}><label htmlFor="rename">当前会话名称</label><div className="action-row"><input id="rename" name="rename" defaultValue={session.name} maxLength={48} required/><button>保存</button></div></form>}<p className="hint">添加到主屏幕：Safari 分享 → 添加到主屏幕。<br/>Mac 需保持开机和联网；锁屏不会结束会话，电脑重启会结束运行中的程序。</p><button className="wide" onClick={async()=>{try{await api('/logout','POST');setAuth(false);setSheet(null);}catch{setToast('退出失败，请重试。');}}}><LogOut size={18}/>退出登录</button></>}
 </section></div>}
 </main>;
}
